version: '3'
 
services:
  mysql:
    build: ./mysql/
    container_name: mysql-server
    ports:
      - "4000:3306"
    volumes:
      - /home/vagrant/data/mysql/university.sql:/docker-entrypoint-initdb.d/university.sql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
  python:
    build: ./python/
    container_name: python-app
    volumes:
      - maps:/tmp     
    depends_on:
      - mysql

volumes:
  maps:

